Syntax highlighter new theme (a11y)
italia/bootstrap-italia pull request #1031
Opened 2023-12-04 14:38 UTC by astagi

## Descrizione

Fixes #1030 

## Checklist

- [ ] Le modifiche sono conformi alle [linee guida di design](https://designers.italia.it/linee-guida).
- [ ] Il codice è coerente con le [indicazioni di progetto](https://italia.github.io/bootstrap-italia/docs/come-iniziare/).
- [ ] Le modifiche sono state verificate sui [Browser supportati](https://getbootstrap.com/docs/5.2/getting-started/browsers-devices/) e per diverse risoluzioni dello schermo.
- [ ] Sono stati effettuati test di accessibilità in ottemperanza a quanto descritto nell'[area "Accessibilità" delle linee guida di design](https://docs.italia.it/italia/designers-italia/manuale-operativo-design-docs/it/versione-corrente/doc/esperienza-utente/accessibilita.html).
- [ ] La documentazione è stata aggiornata.

2023-12-05 08:04 UTC, Virtute90 commented
Devo dire che il nuovo tema colori è più chiaro del precendere!

2023-12-05 10:41 UTC, Fupete commented
@astagi Bel lavoro. 

Segnalerei almeno in un commento che il tema è ispirato a https://github.com/ericwbailey/a11y-syntax-highlighting (che usiamo nella documentazione del design system). Seppur non avendo possibilità di mettere bianchi i caratteri neutri (<>/[]...) ma dovendo colorare tutti i token. 

Rispetto al lavoro secondo me si può ancora ottimizzare: 
- il peso del carattere: togliendo i "font-weight: bold" e lasciando tutto regular
- mettendo font-size a 16px o 1rem (e non 14px come ora).

2023-12-05 10:41 UTC, Fupete requested changes
@astagi Bel lavoro.

Segnalerei almeno in un commento che il tema è ispirato a https://github.com/ericwbailey/a11y-syntax-highlighting (che usiamo nella documentazione del design system). Seppur non avendo possibilità di mettere bianchi i caratteri neutri (<>/[]...) ma dovendo colorare tutti i token.

Rispetto al lavoro secondo me si può ancora ottimizzare:

    il peso del carattere: togliendo i "font-weight: bold" e lasciando tutto regular
    mettendo font-size a 16px o 1rem (e non 14px come ora).

2023-12-05 13:09 UTC, astagi commented
> Devo dire che il nuovo tema colori è più chiaro del precendere!

Grazie @Virtute90 !

2023-12-05 13:10 UTC, astagi commented
> @astagi Bel lavoro.
> 
> Segnalerei almeno in un commento che il tema è ispirato a https://github.com/ericwbailey/a11y-syntax-highlighting (che usiamo nella documentazione del design system). Seppur non avendo possibilità di mettere bianchi i caratteri neutri (<>/[]...) ma dovendo colorare tutti i token.
> 
> Rispetto al lavoro secondo me si può ancora ottimizzare:
> 
> * il peso del carattere: togliendo i "font-weight: bold" e lasciando tutto regular;
> * font-size a 16px o 1rem (e non 14px come ora).

Si lo scrivo nella release!

Va bene procedo alle modifiche.

2023-12-05 13:44 UTC, Fupete requested changes
@astagi continuo a vedere renderizzato `font-size: 14px`. Ci sono almeno altre due classi nei CSS che intervengono 🤷

2023-12-05 13:57 UTC, astagi commented
> @astagi continuo a vedere renderizzato `font-size: 14px`. Ci sono almeno altre due classi nei CSS che intervengono 🤷

Si è vero.. un scss che mi sembra un refuso.. indagherò per ora l'ho fixato lì. Se ti torna tutto mergiamo, grazie!

2023-12-05 15:20 UTC, Fupete approved these changes
Per me va bene. Fai controllare anche a @zetareticoli, non vorrei che il 14px derivasse dai `code` inline...

2023-12-06 11:04 UTC, zetareticoli commented
il `font-size: .875rem` sembra provenire da bootstrap:
![Screenshot 2023-12-06 alle 12 04 15](https://github.com/italia/bootstrap-italia/assets/69706/100850bd-48cc-448b-9b76-ab868df9c7fc)

L'ultimo fix di @astagi lo porta sempre a `1rem`

2023-12-06 14:05 UTC, merged