fix: modificato il parametro top e width #issue 1119
italia/bootstrap-italia pull request #1121
Opened 2024-05-27 14:02 UTC by andrea-conforto

## Descrizione

Modificati i parametri top e width per chiudere correttamente il rettangolo. Ora la modifica è compatibile anche con Design React Kit.

## Checklist

- [ X ] Le modifiche sono conformi alle [linee guida di design](https://designers.italia.it/linee-guida).
- [ X ] Il codice è coerente con le [indicazioni di progetto](https://italia.github.io/bootstrap-italia/docs/come-iniziare/).
- [ X ] Le modifiche sono state verificate sui [Browser supportati](https://getbootstrap.com/docs/5.2/getting-started/browsers-devices/) e per diverse risoluzioni dello schermo.
- [ X ] Sono stati effettuati test di accessibilità in ottemperanza a quanto descritto nell'[area "Accessibilità" delle linee guida di design](https://docs.italia.it/italia/designers-italia/manuale-operativo-design-docs/it/versione-corrente/doc/esperienza-utente/accessibilita.html).
- [ ] La documentazione è stata aggiornata.

2024-05-28 09:00 UTC, zetareticoli requested changes
Ho fatto una prova con un titolo lungo, si vede male perché la linea non si adatta (allego screen)

![Screenshot 2024-05-28 alle 10 59 35](https://github.com/italia/bootstrap-italia/assets/69706/852ad433-80a5-4b63-be68-08f16829f518)

2024-05-28 19:10 UTC, andrea-conforto commented
In realtà il problema che hai messo in evidenza è dovuto al parametro max-width che è impostato a 60ch e che sballa sull'uso di testi più lunghi. Questo parametro nel Design React Kit e impostato a none per permettere un callout più "largo" e di conseguenza espone a titoli più larghi. 

Se invece non si vuole avere limite di testo è importate intanto togliere il max-width e poi impostare in ::after il width in modo tale che, in base alla dimensione del testo e dello schermo lui si vada a calcolare da solo il valore necessario. Questo l'ho fatto con calc(100vw - 100% - 20px). Sotto ti riporto le modifiche:

_callout.scs da 1 a 12:
```
.callout {
  position: relative;
/* max-width: 60ch; <<<  NON SERVE*/
  overflow: hidden;

  .callout-inner {
    padding: 2rem;
    border: 2px solid;
    border-top: 0;
    border-color: $color-border-secondary;
    margin: 2.5rem 0;
  }
```

_callout.scs da 217 a 250:
```
  // standard title
  &:not(.callout-highlight):not(.callout-more) {
    .callout-title {
      position: relative;
      padding-left: 1.5rem;
      top: -3rem;
      .text {
        position: relative;
        overflow: hidden;
        width: 100%;
        /* font-size: 0.875rem; <<<  NON SERVE*/
        padding-right: 1.5rem;
        @include media-breakpoint-up(md) {
          font-size: 1.15rem;
        }
      }
      .text:after {
        content: '';
        top: 0.775em;
        border-top: 2px solid;
        position: absolute;
        width: calc(100vw - 100% - 20px);
        left: 100%;
      }
      &:before {
        content: '';
        top: 0.775em;
        border-top: 2px solid;
        position: absolute;
        width: 3rem;
        left: -2.5rem;
      }
    }
  }
```

Con queste modifiche ottieni un testo ultralungo come da immagine allegata: 
![correzione](https://github.com/italia/bootstrap-italia/assets/18142758/29902732-58f6-42f4-82d9-f773829a4fd7)

Ho notato un problema solo ridimensionando la finestre del browser in "dimensioni" anomale, ma sto indagando dove incontra il problema del ridimensionamento. Nelle dimensioni standard degli schermi invece non ci sono "problemi" di ridimensionamento. 

Fammi sapere se devo postare la modifica

2024-05-30 14:06 UTC, zetareticoli requested changes

2024-05-30 14:06 UTC, zetareticoli commented on src/scss/custom/_callout.scss
> +  max-width: none;
Se deve essere a `none` non si può rimuovere?

2024-05-30 14:06 UTC, zetareticoli commented on src/scss/custom/_callout.scss
> +    &:not(.callout-highlight):not(.callout-more) {
Attenzione: questa modifica genera un bug, nel caso del Callout Highlight il titolo non si vede perché traslato in alto (vedi screen da inspector allegato)

![Screenshot 2024-05-30 alle 16 06 05](https://github.com/italia/bootstrap-italia/assets/69706/627a2061-d9b1-4fa6-9290-885672b3adfc)

2024-05-30 14:16 UTC, andrea-conforto commented on src/scss/custom/_callout.scss
> +  max-width: none;
Qui più che altro è un "refuso". Nelle varie prove di dimensione alla fine l'ho messa a none ma effettivamente si può rimuovere.

2024-05-30 14:18 UTC, andrea-conforto commented on src/scss/custom/_callout.scss
> +    &:not(.callout-highlight):not(.callout-more) {
Controllo anche questa. Mi è sfuggita.

2024-05-30 17:05 UTC, zetareticoli requested changes
Bene il `fix` sul bug del titolo.

Notavo che comunque a risoluzioni mobile il problema della lunghezza del titolo e della riga non si risolve.

Forse potremmo implementare in questa PR il layout mobile previsto fa UI Kit Italia?

![callout-mobile](https://github.com/italia/bootstrap-italia/assets/69706/e33bb053-e4b7-48e8-87ee-fb08460f9f7e)

2024-05-30 19:38 UTC, andrea-conforto commented
Implementare la versione mobile della versione UI Kit è un po complicato perché vanno riscritte le classi mobile affinché in fase di ridimensionamento coincidano con quelle standard e consentano il cambio di stile. Ho studiato gli stili CSS di UI Kit che ho trovato su Figma ma hanno nomi, margini e allineamenti diversi da questa versione. Andrebbe "unificata" anche la visualizzazione. In questa versione infatti il bordo è squadrato e la linea superiore "poggia" su due line verticali, nella versione UI Kit sia standard che mobile il bordo è stondato e questo implica più codice.  

Gli elementi icone, titolo e testo in UI Kit sono allineati  in modo diverso fra standard e mobile. Il titolo e l'icona centrata nel mobile recupera spazio, ma non di tanto (due lettere). Il testo centrato nel mobile non recupera spazio, crea problemi perché  si rende necessario specificare molto più codice per evitare che il browser non confonda lo stile. Conviene l'allineamento testo a sinistra anche nel mobile al posto dell'allineamento centrale.

Restando fedeli alle line guida, la callout deve avere un titolo breve ed un testo coinciso. La quadra con il testo lungo non creo si ottenga nemmeno con la versione UI Kit, ma ci posso provare... mi ci vuole un po, ma ci posso provare...

2024-06-03 15:46 UTC, zetareticoli approved these changes

2024-06-04 14:31 UTC, merged