Update fonts and added italic variants using google-webfonts-helper
italia/bootstrap-italia pull request #582
Opened 2022-01-14 08:48 UTC by mfortini

Added italic fonts and used [google webfonts helper](https://google-webfonts-helper.herokuapp.com/fonts) to configure fonts

Look at the "mobile first" string in the examples below:

Before:
![image](https://user-images.githubusercontent.com/1104926/149485717-4293e0d8-83cf-4908-bdbf-24d16cb66fbd.png)

After:
![image](https://user-images.githubusercontent.com/1104926/149485878-234ab431-384b-4cbd-9849-e6d0d5280c36.png)

2022-01-16 21:00 UTC, astagi requested changes
@mfortini seems that google-webfonts-helper deleted some license files , is it possible to bring them back?

2022-01-17 18:00 UTC, mfortini commented
@astagi I restored the license files

2022-01-18 08:13 UTC, astagi approved these changes

2022-01-18 08:13 UTC, merged

2022-01-18 08:13 UTC, astagi commented
thank you @mfortini