docs(a11y): implemented modal aria-labelledby in examples
italia/bootstrap-italia pull request #587
Opened 2022-01-14 14:26 UTC by gpeirolo

## Descrizione
Fixes #555 

Modificato il codice degli esempi con un uso corretto dell'attributo aria-labelledby della modale associato al titolo della modale stessa.

## Checklist

- [ ] Le modifiche sono conformi alle [linee guida di design](https://docs.italia.it/italia/designers-italia/design-linee-guida-docs/).
- [ ] Il codice è coerente con le [indicazioni di progetto](https://italia.github.io/bootstrap-italia/docs/come-iniziare/).
- [ ] Le modifiche sono state verificate sui [Browser supportati](https://getbootstrap.com/docs/4.6/getting-started/browsers-devices/) e per diverse risoluzioni dello schermo.
- [ ] Sono stati effettuati test di accessibilità in ottemperanza a quanto descritto nell'[area "Accessibilità" delle linee guida di design](https://docs.italia.it/italia/designers-italia/design-linee-guida-docs/it/stabile/doc/service-design/accessibilita.html).
- [x] La documentazione è stata aggiornata.

2022-01-14 15:06 UTC, gpeirolo commented
![](https://github.trello.services/images/mini-trello-icon.png) [Primi fix accessibilità (da issue github BI)](https://trello.com/c/haWLqzbT/122-primi-fix-accessibilit%C3%A0-da-issue-github-bi)

2022-01-17 07:05 UTC, astagi requested changes
@gpeirolo aggiungerei in coda a questa PR anche un esempio con `aria-describedby`, [qua](https://github.com/italia/bootstrap-italia/pull/587/files#diff-c8630990680a4b3ac8babea52d3b7fe033a9777a76b633c23161425a65cf8819L185) vedo è stata cancellata.

2022-01-17 09:47 UTC, gpeirolo commented
@astagi gli `aria-describedby` eliminati non avevano senso in quel contesto. Ho aggiunto l'attributo ad uno degli esempi ed aggiornato il blocco **Accessibilità** della documentazione con indicazioni relative all'uso di `aria-label` quando non è presente un titolo della modale.

2022-01-17 10:43 UTC, astagi commented
> @astagi gli `aria-describedby` eliminati non avevano senso in quel contesto. Ho aggiunto l'attributo ad uno degli esempi ed aggiornato il blocco **Accessibilità** della documentazione con indicazioni relative all'uso di `aria-label` quando non è presente un titolo della modale.

si concordo! il mio messaggio era relativo al fatto di aggiungere comunque un esempio con `aria-describedby` in quanto citato nella documentazione. Visto il commit, grazie @gpeirolo

2022-01-17 10:43 UTC, merged