Feat/splide carousel 376
italia/bootstrap-italia pull request #622
Opened 2022-02-03 09:42 UTC by OscarBresolin

Inserimento nuovo plugin Splide per carousel.
## Descrizione
- Rimozione di Owl carousel dal bundle ed importazione come libreria esterna
- Inserimento di Splide ed importazione come libreria esterna
- Modifica documentazione e aggiunta di nuova sezione. Pagina Carousel Legacy (Owl), Pagina Carousel (Splide)

Fixes #376

## Checklist

- [X] Le modifiche sono conformi alle [linee guida di design](https://docs.italia.it/italia/designers-italia/design-linee-guida-docs/).
- [X] Il codice è coerente con le [indicazioni di progetto](https://italia.github.io/bootstrap-italia/docs/come-iniziare/).
- [X] Le modifiche sono state verificate sui [Browser supportati](https://getbootstrap.com/docs/4.6/getting-started/browsers-devices/) e per diverse risoluzioni dello schermo.
- [X] Sono stati effettuati test di accessibilità in ottemperanza a quanto descritto nell'[area "Accessibilità" delle linee guida di design](https://docs.italia.it/italia/designers-italia/design-linee-guida-docs/it/stabile/doc/service-design/accessibilita.html).
- [X] La documentazione è stata aggiornata.

2022-02-03 09:52 UTC, gpeirolo commented
![](https://github.trello.services/images/mini-trello-icon.png) [Fix accessibilità BI individuate](https://trello.com/c/Zgk9Abqb/99-fix-accessibilit%C3%A0-bi-individuate)

2022-02-03 09:53 UTC, gpeirolo commented
![](https://github.trello.services/images/mini-trello-icon.png) [Verificare ultime PR BI > es. swiper](https://trello.com/c/V315krOb/123-verificare-ultime-pr-bi-es-swiper)

2022-02-03 15:40 UTC, astagi requested changes
Separate css for Owl and Splide

2022-02-10 14:20 UTC, astagi commented
@OscarBresolin @gpeirolo da vedere se si risolve facilmente anche questa issue https://github.com/italia/bootstrap-italia/issues/455 (modalità loop del carousel). La metto tra le issue che risolve possiamo lavorarci su questo branch

2022-02-10 14:24 UTC, OscarBresolin commented
> @OscarBresolin @gpeirolo da vedere se si risolve facilmente anche questa issue #455 (modalità loop del carousel). La metto tra le issue che risolve possiamo lavorarci su questo branch

Ci do un'occhiata

2022-03-03 12:58 UTC, astagi commented
@OscarBresolin ho mergiato la parte di origin/master qua dentro in modo da riallineare tutto.

2022-03-08 07:23 UTC, astagi approved these changes

2022-03-08 07:23 UTC, merged