Fix/header a11y review d83
italia/bootstrap-italia pull request #642
Opened 2022-02-17 14:47 UTC by gpeirolo

## Descrizione
Risoluzione dei problemi noti di accessibilità relativi all'header / navigazione.

NB: per consentire un test focalizzato sull'header la documentazione non è stata aggiornata (/docs/menu-di-navigazione/header/) ma è stata creata una pagina ad-hoc /docs/esempi/header/

A seguito di verifica AGID ed eventuali ulteriori modifiche si procederà con l'aggiornamento della documentazione e degli altri esempi.

## Checklist

- [ ] Le modifiche sono conformi alle [linee guida di design](https://docs.italia.it/italia/designers-italia/design-linee-guida-docs/).
- [x] Il codice è coerente con le [indicazioni di progetto](https://italia.github.io/bootstrap-italia/docs/come-iniziare/).
- [x] Le modifiche sono state verificate sui [Browser supportati](https://getbootstrap.com/docs/4.6/getting-started/browsers-devices/) e per diverse risoluzioni dello schermo.
- [x] Sono stati effettuati test di accessibilità in ottemperanza a quanto descritto nell'[area "Accessibilità" delle linee guida di design](https://docs.italia.it/italia/designers-italia/design-linee-guida-docs/it/stabile/doc/service-design/accessibilita.html).
- [ ] La documentazione è stata aggiornata.

2022-02-21 09:48 UTC, astagi requested changes
Rimuovere il codice commentato invece di commentarlo

2022-02-21 14:55 UTC, gpeirolo commented
> * Rimuovere il codice commentato invece di commentarlo.

Fatto.

> * Aggiungere l'esempio nella pagina [esempi](https://italia.github.io/bootstrap-italia/docs/esempi/)

Attendo verifica di AGID.

2022-02-21 15:27 UTC, astagi commented
> > * Rimuovere il codice commentato invece di commentarlo.
> 
> Fatto.
> 
> > * Aggiungere l'esempio nella pagina [esempi](https://italia.github.io/bootstrap-italia/docs/esempi/)
> 
> Attendo verifica di AGID.

Grazie @gpeirolo

2022-03-08 07:58 UTC, astagi approved these changes

2022-03-08 08:24 UTC, astagi approved these changes

2022-03-08 09:30 UTC, merged