fix timeline pin-wrapper #712
italia/bootstrap-italia pull request #714
Opened 2022-09-02 13:36 UTC by arturu

Come segnalato con #712 propongo questo cambiamento

## Descrizione

## Checklist

- [ ] Le modifiche sono conformi alle [linee guida di design](https://designers.italia.it/linee-guida).
- [ ] Il codice è coerente con le [indicazioni di progetto](https://italia.github.io/bootstrap-italia/docs/come-iniziare/).
- [ ] Le modifiche sono state verificate sui [Browser supportati](https://getbootstrap.com/docs/5.1/getting-started/browsers-devices/) e per diverse risoluzioni dello schermo.
- [ ] Sono stati effettuati test di accessibilità in ottemperanza a quanto descritto nell'[area "Accessibilità" delle linee guida di design](https://docs.italia.it/italia/designers-italia/manuale-operativo-design-docs/it/versione-corrente/doc/esperienza-utente/accessibilita.html).
- [ ] La documentazione è stata aggiornata.

2022-09-02 14:10 UTC, astagi commented
@arturu mergia pure l'ultimo `main` ci sono dei conflitti da risolvere sul file scss :)

2022-09-02 18:25 UTC, astagi requested changes
Ribasare il branch con main

2022-09-05 14:29 UTC, astagi commented
@arturu forse questa PR può risolvere il problema definitivamente https://github.com/italia/bootstrap-italia/pull/717 che ne dici?

2022-09-05 15:22 UTC, arturu commented
Ho provato #717 ma non mi sta funzionando, l'elemento `it-pin-wrapper` sta sempre sopra al megamenu

![Schermata del 2022-09-05 17-16-51](https://user-images.githubusercontent.com/4628942/188480547-83f8d9c8-91a7-4ca5-90c1-1f38577c6ec4.png)

ho verificato che non sia un problema di cache ma 2 modifiche le ha prese e non sto vedendo una cache di Drupal.

2022-09-08 14:08 UTC, astagi commented
@arturu ho mergiato la parte di fix di @OscarBresolin , questa parte del calc che divide per 2 è ancora valida alla risoluzione del componente? se si possiamo chiudere questa PR e ne apriamo un'altra con solo quel fix che non incide su z-index che ne dici?

2022-09-08 15:39 UTC, closed without merging