docs:fix spelling error
italia/bootstrap-italia pull request #778
Opened 2022-11-19 16:48 UTC by DomeT99

## Descrizione
Dopo aver creato una PR riguardante la issue #741 , mi sono accorto di un errore ortografico che ho tempestivamente corretto.

## Checklist

- [x] Le modifiche sono conformi alle [linee guida di design](https://designers.italia.it/linee-guida).
- [x] Il codice è coerente con le [indicazioni di progetto](https://italia.github.io/bootstrap-italia/docs/come-iniziare/).
- [x] Le modifiche sono state verificate sui [Browser supportati](https://getbootstrap.com/docs/5.1/getting-started/browsers-devices/) e per diverse risoluzioni dello schermo.
- [x] Sono stati effettuati test di accessibilità in ottemperanza a quanto descritto nell'[area "Accessibilità" delle linee guida di design](https://docs.italia.it/italia/designers-italia/manuale-operativo-design-docs/it/versione-corrente/doc/esperienza-utente/accessibilita.html).
- [x] La documentazione è stata aggiornata.

2022-11-19 17:37 UTC, Fupete requested changes
Cambierei anche `class` con `classe` sullo stesso rigo.

2022-11-19 17:43 UTC, DomeT99 commented
Certo, nessun problema.

2022-11-19 18:07 UTC, Fupete approved these changes

2022-11-21 13:28 UTC, astagi approved these changes

2022-11-21 13:28 UTC, merged