feat: aggiunto btn per copiare il codice nella clipboard
italia/bootstrap-italia pull request #972
Opened 2023-09-28 13:12 UTC by Virtute90

## Descrizione

Nuova features per copia il codice nella clipboard con un clip, molto comodo
![image](https://github.com/italia/bootstrap-italia/assets/32056724/fd352edd-7d33-430c-babc-77ca88d0c491)

## Miglioramenti proposti

Il div contenitore sarebbe da settare in overlay per una migliore visualizzazione.

## Checklist

- [x] Le modifiche sono conformi alle [linee guida di design](https://designers.italia.it/linee-guida).
- [x] Il codice è coerente con le [indicazioni di progetto](https://italia.github.io/bootstrap-italia/docs/come-iniziare/).
- [x] Le modifiche sono state verificate sui [Browser supportati](https://getbootstrap.com/docs/5.2/getting-started/browsers-devices/) e per diverse risoluzioni dello schermo.
- [x] Sono stati effettuati test di accessibilità in ottemperanza a quanto descritto nell'[area "Accessibilità" delle linee guida di design](https://docs.italia.it/italia/designers-italia/manuale-operativo-design-docs/it/versione-corrente/doc/esperienza-utente/accessibilita.html).
- [x] La documentazione è stata aggiornata.

2023-10-02 13:35 UTC, astagi commented
Grazie @Virtute90 molto utile! secondo te è possibile estenderlo su tutte le parti coding? ad esempio, qua in una c'è nell'altra no..

<img width="1003" alt="image" src="https://github.com/italia/bootstrap-italia/assets/537363/e3805cce-6d23-4245-ba26-012ec0d99192">

2023-10-02 13:44 UTC, Virtute90 commented
> Grazie @Virtute90 molto utile! secondo te è possibile estenderlo su tutte le parti coding? ad esempio, qua in una c'è nell'altra no..
> 
> <img alt="image" width="1003" src="https://user-images.githubusercontent.com/537363/271984746-e3805cce-6d23-4245-ba26-012ec0d99192.png">

Domani controllo e ti so dire

2023-10-03 07:42 UTC, Virtute90 commented
> Grazie @Virtute90 molto utile! secondo te è possibile estenderlo su tutte le parti coding? ad esempio, qua in una c'è nell'altra no..
> 
> <img alt="image" width="1003" src="https://user-images.githubusercontent.com/537363/271984746-e3805cce-6d23-4245-ba26-012ec0d99192.png">

Il bottone viene aggiunto al codice generato nel template con 
```
{% capture example %}
{% endcapture %}{% include example.html content=example %}
```
invece non viene considerato quello generato con
```
> ``` html
> ``` 
```

Avrei già la modifica da integrare, procedo?

Secondo quello generato con ''' html sono solo esempi e forse non sono da copiare...

2023-10-04 12:33 UTC, astagi commented
> > Grazie @Virtute90 molto utile! secondo te è possibile estenderlo su tutte le parti coding? ad esempio, qua in una c'è nell'altra no..
> > <img alt="image" width="1003" src="https://user-images.githubusercontent.com/537363/271984746-e3805cce-6d23-4245-ba26-012ec0d99192.png">
> 
> Il bottone viene aggiunto al codice generato nel template con
> 
> ```
> {% capture example %}
> {% endcapture %}{% include example.html content=example %}
> ```
> 
> invece non viene considerato quello generato con
> 
> ```
> > ``` html
> > ``` 
> ```
> 
> Avrei già la modifica da integrare, procedo?
> 
> Secondo quello generato con ''' html sono solo esempi e forse non sono da copiare...

Grazie @Virtute90 sisi procedi pure a questo punto includiamo anche quegli snippet, male non fa :)

2023-10-05 07:29 UTC, Virtute90 commented
> > > Grazie @Virtute90 molto utile! secondo te è possibile estenderlo su tutte le parti coding? ad esempio, qua in una c'è nell'altra no..
> > > <img alt="image" width="1003" src="https://user-images.githubusercontent.com/537363/271984746-e3805cce-6d23-4245-ba26-012ec0d99192.png">
> > 
> > 
> > Il bottone viene aggiunto al codice generato nel template con
> > ```
> > {% capture example %}
> > {% endcapture %}{% include example.html content=example %}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > invece non viene considerato quello generato con
> > ```
> > > ``` html
> > > ``` 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Avrei già la modifica da integrare, procedo?
> > Secondo quello generato con ''' html sono solo esempi e forse non sono da copiare...
> 
> Grazie @Virtute90 sisi procedi pure a questo punto includiamo anche quegli snippet, male non fa :)

Aggiunto commit

2023-10-05 13:46 UTC, astagi requested changes
@Virtute90 due cose di review:

- Farei un'unica funzione di copia per non avere il codice duplicato
- Invece di `Copy code to clipboard` mettere in italiano `Copia il codice negli appunti`

Grazie mille!

2023-10-06 10:04 UTC, Virtute90 commented
> @Virtute90 due cose di review:
> 
> * Farei un'unica funzione di copia per non avere il codice duplicato
> * Invece di `Copy code to clipboard` mettere in italiano `Copia il codice negli appunti`
> 
> Grazie mille!

Fatto!

2023-10-06 11:49 UTC, astagi commented
> > @Virtute90 due cose di review:
> > 
> > * Farei un'unica funzione di copia per non avere il codice duplicato
> > * Invece di `Copy code to clipboard` mettere in italiano `Copia il codice negli appunti`
> > 
> > Grazie mille!
> 
> Fatto!
> 
> ps: come posso contattarti? dovrei chiederti una cosa 😅

Grazie mille! :) Certamente, mi trovi come Andrea Stagi sullo Slack pubblico di `Developers Italia` 👍

2023-10-06 13:36 UTC, astagi commented
@Virtute90 ho fatto un piccolo fix per ripristinare il bottone dopo 5 secondi e spostato in alto a destra, che ne dici?

2023-10-06 13:44 UTC, Virtute90 commented
> @Virtute90 ho fatto un piccolo fix per ripristinare il bottone dopo 5 secondi e spostato in alto a destra, che ne dici?

Ho visto, mi piace il ripristino del bottone ed è più allineato al box!

2023-10-09 09:11 UTC, merged